### ISSUE TITLE
PDF -> JPEG

### ISSUE THREAD

**Issue by andrewbo29** [andrewbo29/al_maqrizi#1]

**Comment by alex-senov** [comment]
Чтобы не забыть
http://stackoverflow.com/questions/9710118/convert-multipage-pdf-to-png-and-back-linux

**Comment by alex-senov** [comment]
Все верно, утилита [convert](http://www.imagemagick.org/script/convert.php) из imagemagick подходит.

### Примеры применения

1) С указанием числа пикселей на дюйм (не очень удобно, имхо):

```
convert -density 100x100  multipage.pdf page_%d.png
```

2) С указанием ширины в пикселях (высота подгоняется автоматически, чтобы сохранить соотношение сторон):

```
convert -resize 1024  multipage.pdf page_%d.png
```

3) С указанием высоты в пикселях (ширина подгоняется автоматически, чтобы сохранить соотношение сторон):

```
convert -resize x768  multipage.pdf page_%d.png
```

Вообщем там можно сильно углубиться в то, как менять разрешение/размеры изображения. Есть, например, [объяснение на stackoverflow](http://stackoverflow.com/questions/8517304/what-is-the-difference-for-sample-resample-scale-resize-adaptive-resize-thumbnai), но я там мало что понял. Имхо набора выше нам хватит.

**Замечание**. У меня во время выполнения одной из команд выше для 70-страничной pdf-ки компьютр подвис на пару минут.

**Comment by alex-senov** [comment]
@andrewbo29, ты можешь все исходные картинки (включая pdf) где-нибудь расшарить (в репозитории, например)?
