### ISSUE TITLE
Удалённый сервер для вычислений с GPU

### ISSUE THREAD

**Issue by andrewbo29** [andrewbo29/al_maqrizi#2]

**Comment by alex-senov** [comment]
Пока буду писать сюда, позже мб перенесу в вики.

## Amazon GPU instance

[Список всех типов серверов](https://aws.amazon.com/ec2/instance-types/).
Рассматривается вариант g2.2xlarge (для серьезных ребят есть еще g2.8xlarge).

### По поводу цены

Есть два варианта платы за сервер: on-demand и spot (на самом деле есть еще и reserved, но он не для нищебродов). On-Demand --- почасовая оплата. Spot --- "аукцион": ты ставишь ставку (часовую стоимость) и если твоя ставка выше чем у большинства, то сервер идет к тебе, но если твою ставку перебьют, то твой сервер может перейти к более щедрому, а твои расчеты потеряются. Пару раз пробовал использовать spot, ни разу никто не перебивал.
Цена spot по какой-то причине очень сильно варьируется в зависимости от региона сервера, поэтому буду приводить цены для нескольких регионов.

Данные по ценам [здесь](https://aws.amazon.com/ec2/pricing/), а по характеристикам различных типов серверов [тут](https://aws.amazon.com/ec2/instance-types/).

**Comment by alex-senov** [comment]
### g2.2xlarge

##### Характеристики

| Характеристика | Значение |
| --- | --- |
| GPU | 1 x [GRID K520, 1.536 cores, 4GB](http://www.nvidia.ru/object/cloud-gaming-gpu-boards-ru.html) |
| CPU | 1 x [Intel Xeon, 8 cores, 2.GHz](http://ark.intel.com/products/64595/Intel-Xeon-Processor-E5-2670-20M-Cache-2_60-GHz-8_00-GTs-Intel-QPI) |
| Memory | 15 GB |
| Storage | 1 x 60GB SSD |

##### Цена

| Тип | Стоимость |
| --- | --- |
| On-demand | $0.65-0.77 / hour |
| Spot US-East | $0.16001 / hour |
| Spot US-West1 | $0.6501 / hour |
| Spot US-West2 | $0.16001 / hour |
| Spot EU-Ireland | $0.2674 / hour |
| Spot EU-Frankfurt | $0.1971 / hour |

**Comment by alex-senov** [comment]
### g2.8xlarge

##### Характеристики

| Характеристика | Значение |
| --- | --- |
| GPU | 4 x [GRID K520, 1.536 cores, 4GB](http://www.nvidia.ru/object/cloud-gaming-gpu-boards-ru.html) |
| CPU | 4 x [Intel Xeon, 8 cores, 2.GHz](http://ark.intel.com/products/64595/Intel-Xeon-Processor-E5-2670-20M-Cache-2_60-GHz-8_00-GTs-Intel-QPI) |
| Memory | 60 GB |
| Storage | 2 x 120GB SSD |

##### Цена

| Тип | Стоимость |
| --- | --- |
| On-demand | $2.6-3.1 / hour |
| Spot US-East | $0.5876 / hour |
| Spot US-West1 | $0.64004 / hour |
| Spot US-West2 | $0.5148 / hour |
| Spot EU-Ireland | $0.6759 / hour |
| Spot EU-Frankfurt | $0.64004 / hour |

Можно заметить, что  в US-West1 **_g2.8xlarge дешевле чем g2.2xlarge_** !!!

**Comment by alex-senov** [comment]
В качестве вывода, если таблички не врут и можно за 60 центов арендовать мега мощный g2.8xlarge, то я бы так и сделал. 
Обкатить весь процесс деплоя, включения-отключения и т.п. можно на каком-нибудь t2.small (3 цента за час), а как обкатаем --- перейти на g2.8xlarge и проверять наши гипотезы быстро-быстро.
